POLKIT_PATH="/usr/share/polkit-1"
POLKIT_PATH_ACTIONS="$POLKIT_PATH/actions"
POLKIT_PATH_RULES="$POLKIT_PATH/rules.d"
PKEXEC_DEBHELPER_PATH="/usr/share/pkexec-debhelper/"
POLKIT_SKEL_FILE="$PKEXEC_DEBHELPER_PATH/skel/polkit.skel"
